create table currency_rates (
    rate float4 not null,
    datetime timestamp(6),
    id bigint generated by default as identity,
    currency_from CHAR(3) not null check (currency_from in ('KZT','USD','RUB')),
    currency_to CHAR(3) not null check (currency_to in ('KZT','USD','RUB')),
    primary key (id)
)

