create table limits (
    sum float4,
    datetime timestamp(6),
    id bigint generated by default as identity,
    currency_shortname CHAR(3) not null check (currency_shortname in ('KZT','USD','RUB')),
    expense_category varchar(255) not null check (expense_category in ('GOOD','SERVICE')),
    month_year CHAR(7) not null,
    primary key (id)
)