create table transactions (
    amount float4,
    limit_exceeded boolean not null,
    usd_sum float4 not null,
    datetime timestamp(6),
    id bigint generated by default as identity,
    account_from CHAR(10) not null,
    account_to CHAR(10) not null,
    currency_shortname CHAR(3) not null check (currency_shortname in ('KZT','USD','RUB')),
    expense_category varchar(255) not null check (expense_category in ('GOOD','SERVICE')),
    month_year CHAR(7) not null,
    primary key (id)
)